#version 450

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) readonly buffer XBuf { float x[]; };
layout(binding = 1) readonly buffer WBuf { float weights[]; };
layout(binding = 2) writeonly buffer DstBuf { float dst[]; };

layout(push_constant) uniform PushConstants {
    uint n_outputs;
    uint n_embd;
    uint dispatch_x;
    uint x_nb1;
    uint x_nb2;
    uint w_nb1;
    uint d_nb1;
};

const uint HC = 4;

void main() {
    const uint workgroup_idx = gl_WorkGroupID.y * dispatch_x + gl_WorkGroupID.x;
    const uint output_idx = workgroup_idx * gl_WorkGroupSize.x + gl_LocalInvocationID.x;

    if (output_idx >= n_outputs) {
        return;
    }

    const uint i = output_idx % n_embd;
    const uint t = output_idx / n_embd;

    float sum = 0.0;
    for (uint h = 0; h < HC; ++h) {
        sum += x[i + h * x_nb1 + t * x_nb2] * weights[h + t * w_nb1];
    }
    dst[i + t * d_nb1] = sum;
}
